apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.ObjectMeta.Name}}-prometheus-pushgateway"
  namespace: "{{.ObjectMeta.Namespace}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/created-by: controller-manager
      app.kubernetes.io/instance: "{{.ObjectMeta.Name}}"
      app.kubernetes.io/name: GlideinSetCollection
      gmos.chtc.wisc.edu/app: prometheus-pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/created-by: controller-manager
        app.kubernetes.io/instance: "{{.ObjectMeta.Name}}"
        app.kubernetes.io/name: GlideinSetCollection
        gmos.chtc.wisc.edu/app: prometheus-pushgateway
    spec:
      containers:
      - image: prom/pushgateway
        imagePullPolicy: IfNotPresent
        name: prometheus-pushgateway
        resources: {}
