apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/instance: "{{ .ObjectMeta.Name }}"
    app.kubernetes.io/name: GlideinSetCollection
  name: "{{ .ObjectMeta.Name }}-prometheus"
  namespace: "{{ .ObjectMeta.Namespace }}"
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    gmos.chtc.wisc.edu/app: prometheus
