apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers: []
    scrape_configs:
      {{ if and (.Spec.Prometheus.ServiceAccount) (not (eq .Spec.Prometheus.ServiceAccount "default")) }}
      - job_name: 'node-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        metric_relabel_configs:
          - source_labels: [pod]
            regex: {{.ObjectMeta.Name}}-.*
            action: keep
      {{ end }}
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
        - targets: [{{.ObjectMeta.Name}}-prometheus-pushgateway.{{.ObjectMeta.Namespace}}.svc.cluster.local:9091]
        - targets: [{{.ObjectMeta.Name}}-collector.{{.ObjectMeta.Namespace}}.svc.cluster.local:9618]
kind: ConfigMap
metadata:
  name: "{{.ObjectMeta.Name}}-prometheus"
  namespace: "{{.ObjectMeta.Namespace}}"
