apiVersion: v1
data:
  {{ if and (.Data) (len .Data)}}
    {{ range $key, $value := .Data }}
      {{ $key }}: {{ $value | base64 }}
    {{ end }}
  {{ else }}
    sample.cfg: ""
  {{ end }}
kind: Secret
metadata:
  name: '{{ .ObjectMeta.Name }}-data'
  namespace: '{{ .ObjectMeta.Namespace }}'
type: Opaque
