apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .ObjectMeta.Name }}-fluentd-cfg
  namespace: {{ .ObjectMeta.Namespace }}
  labels:
    component: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /pilot/log/*Log*,/pilot/log/supervisord.log,/pilot/startlog/*Log*
      pos_file /tmp/app.logs.pos
      tag app.logs
      <parse>
        @type none
      </parse>
    </source>

    <filter app.logs>
      @type record_transformer
      <record>
        hostname "#{Socket.gethostname}"
        timestamp "${time}"
      </record>
    </filter>

    <match app.logs>
      @type forward
      send_timeout 60s
      recover_wait 10s
      hard_timeout 60s
      <server>
        name central_fluentd
        host {{ .Spec.ParentName }}-fluentd.{{ .ObjectMeta.Namespace }}.svc.cluster.local
        port 24224
      </server>

    </match>
