# permissions for end users to view glideinsetcollections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: glideinsetcollection-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gmos-k8s-operator
    app.kubernetes.io/part-of: gmos-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: glideinsetcollection-viewer-role
rules:
- apiGroups:
  - gmos.chtc.wisc.edu
  resources:
  - glideinsetcollections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gmos.chtc.wisc.edu
  resources:
  - glideinsetcollections/status
  verbs:
  - get
