apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-06-11T23:20:59Z"
  labels:
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/instance: '{{.ObjectMeta.Name}}'
    app.kubernetes.io/name: GlideinSetCollection
  name: '{{.ObjectMeta.Name}}-collector'
  namespace: '{{.ObjectMeta.Namespace}}'
spec:
  ports:
  - name: collector
    port: 9618
    protocol: TCP
    targetPort: 9618
  selector:
    gmos.chtc.wisc.edu/app: collector
