//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentdMonitoringSpec) DeepCopyInto(out *FluentdMonitoringSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.StorageVolume != nil {
		in, out := &in.StorageVolume, &out.StorageVolume
		*out = new(v1.VolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentdMonitoringSpec.
func (in *FluentdMonitoringSpec) DeepCopy() *FluentdMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(FluentdMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSet) DeepCopyInto(out *GlideinSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.RemoteManifest != nil {
		in, out := &in.RemoteManifest, &out.RemoteManifest
		*out = new(PilotSetNamespaceConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSet.
func (in *GlideinSet) DeepCopy() *GlideinSet {
	if in == nil {
		return nil
	}
	out := new(GlideinSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlideinSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetCollection) DeepCopyInto(out *GlideinSetCollection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetCollection.
func (in *GlideinSetCollection) DeepCopy() *GlideinSetCollection {
	if in == nil {
		return nil
	}
	out := new(GlideinSetCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlideinSetCollection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetCollectionList) DeepCopyInto(out *GlideinSetCollectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlideinSetCollection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetCollectionList.
func (in *GlideinSetCollectionList) DeepCopy() *GlideinSetCollectionList {
	if in == nil {
		return nil
	}
	out := new(GlideinSetCollectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlideinSetCollectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetCollectionSpec) DeepCopyInto(out *GlideinSetCollectionSpec) {
	*out = *in
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.Fluentd.DeepCopyInto(&out.Fluentd)
	if in.GlideinSets != nil {
		in, out := &in.GlideinSets, &out.GlideinSets
		*out = make([]GlideinSetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetCollectionSpec.
func (in *GlideinSetCollectionSpec) DeepCopy() *GlideinSetCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(GlideinSetCollectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetCollectionStatus) DeepCopyInto(out *GlideinSetCollectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetCollectionStatus.
func (in *GlideinSetCollectionStatus) DeepCopy() *GlideinSetCollectionStatus {
	if in == nil {
		return nil
	}
	out := new(GlideinSetCollectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetList) DeepCopyInto(out *GlideinSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlideinSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetList.
func (in *GlideinSetList) DeepCopy() *GlideinSetList {
	if in == nil {
		return nil
	}
	out := new(GlideinSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlideinSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetSpec) DeepCopyInto(out *GlideinSetSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.SecurityContext.DeepCopyInto(&out.SecurityContext)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PilotVolume != nil {
		in, out := &in.PilotVolume, &out.PilotVolume
		*out = new(v1.VolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetSpec.
func (in *GlideinSetSpec) DeepCopy() *GlideinSetSpec {
	if in == nil {
		return nil
	}
	out := new(GlideinSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlideinSetStatus) DeepCopyInto(out *GlideinSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlideinSetStatus.
func (in *GlideinSetStatus) DeepCopy() *GlideinSetStatus {
	if in == nil {
		return nil
	}
	out := new(GlideinSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotSetEnv) DeepCopyInto(out *PilotSetEnv) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotSetEnv.
func (in *PilotSetEnv) DeepCopy() *PilotSetEnv {
	if in == nil {
		return nil
	}
	out := new(PilotSetEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotSetNamespaceConfig) DeepCopyInto(out *PilotSetNamespaceConfig) {
	*out = *in
	out.Security = in.Security
	out.Volume = in.Volume
	out.SecretSource = in.SecretSource
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]PilotSetEnv, len(*in))
		copy(*out, *in)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotSetNamespaceConfig.
func (in *PilotSetNamespaceConfig) DeepCopy() *PilotSetNamespaceConfig {
	if in == nil {
		return nil
	}
	out := new(PilotSetNamespaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotSetSecretSource) DeepCopyInto(out *PilotSetSecretSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotSetSecretSource.
func (in *PilotSetSecretSource) DeepCopy() *PilotSetSecretSource {
	if in == nil {
		return nil
	}
	out := new(PilotSetSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotSetSecurity) DeepCopyInto(out *PilotSetSecurity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotSetSecurity.
func (in *PilotSetSecurity) DeepCopy() *PilotSetSecurity {
	if in == nil {
		return nil
	}
	out := new(PilotSetSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotSetVolumeMount) DeepCopyInto(out *PilotSetVolumeMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotSetVolumeMount.
func (in *PilotSetVolumeMount) DeepCopy() *PilotSetVolumeMount {
	if in == nil {
		return nil
	}
	out := new(PilotSetVolumeMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusMonitoringSpec) DeepCopyInto(out *PrometheusMonitoringSpec) {
	*out = *in
	if in.StorageVolume != nil {
		in, out := &in.StorageVolume, &out.StorageVolume
		*out = new(v1.VolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusMonitoringSpec.
func (in *PrometheusMonitoringSpec) DeepCopy() *PrometheusMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}
