apiVersion: gmos.chtc.wisc.edu/v1alpha1
kind: GlideinManagerPilotSet
metadata:
  labels:
    app.kubernetes.io/name: glideinmanagerpilotset
    app.kubernetes.io/instance: glideinmanagerpilotset-sample
    app.kubernetes.io/part-of: gmos-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gmos-k8s-operator
  name: glideinmanagerpilotset-sample
spec:
  glideinManagerUrl: http://gm-file-server-webservice.dev.svc.cluster.local
  prometheus:
    serviceAccount: default
    storageVolumeSource:
      emptyDir:
        sizeLimit: "5G"
  glideinSets:
  - name: small
    size: 6
    priorityClassName: low-priority
    tolerations:
    - key: "foo"
      operator: "Equal"
      value: "bar"
      effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/hostname: minikube
    resources:
      requests:
        cpu: "200m"
        memory: "100M"
      limits:
        cpu: "200m"
        memory: "100M"
