apiVersion: gmos.chtc.wisc.edu/v1alpha1
kind: GlideinSetCollection
metadata:
  labels:
    app.kubernetes.io/name: glideinsetcollection
    app.kubernetes.io/instance: glideinsetcollection-sample
    app.kubernetes.io/part-of: gmos-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gmos-k8s-operator
  name: glideinset-dev
spec:
  glideinManagerUrl: http://gm-file-server-webservice.dev.svc.cluster.local
  prometheus:
    serviceAccount: default
    storageVolumeSource:
      emptyDir:
        sizeLimit: "5G"

  fluentd:
    storageVolumeSource:
      persistentVolumeClaim:
        claimName: logs-pvc

  glideinSets:
  - name: small
    size: 2 
    priorityClassName: low-priority
    tolerations:
    - key: "foo"
      operator: "Equal"
      value: "bar"
      effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/hostname: minikube
    resources:
      requests:
        cpu: "200m"
        memory: "100M"
      limits:
        cpu: "200m"
        memory: "100M"

  - name: medium
    size: 1
    priorityClassName: medium-priority
    tolerations:
    - key: "foo"
      operator: "Equal"
      value: "bar"
      effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/hostname: minikube
    resources:
      requests:
        cpu: "400m"
        memory: "200M"
      limits:
        cpu: "400m"
        memory: "200M"
