apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
    name: medium-priority
value: 1000
globalDefault: true
description: "Default medium priority class"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
    name: low-priority
value: 100
globalDefault: false
description: "Low priority class for glideins"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
    name: high-priority
value: 10000
globalDefault: false
description: "High priority class for pods that are intended to kick glideins"