apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmos-k8s-operator-controller-manager
  namespace: gmos-k8s-operator-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Never
        env:
        - name: CLIENT_NAME
          value: gmos-k8s-operator-controller-webservice.gmos-k8s-operator-system.svc.cluster.local
        - name: WATCH_NAMESPACE
          value: dev #,prod
