apiVersion: apps/v1
kind: Deployment
metadata:
  name: glidein-manager-controller-manager
  namespace: glidein-manager-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Never
        env:
        - name: CLIENT_NAME
          value: glidein-manager-controller-webservice.glidein-manager-operator.svc.cluster.local
        - name: WATCH_NAMESPACE
          value: dev #,prod
